### Group Prject - London Bike Rentals

In this project, you will work with the London Bikes dataset, which records daily bike rentals in the city along with key variables such as dates, weather conditions, and seasonality.

The goal is to apply the full data analytics workflow:

- Clean and prepare the dataset.

- Explore the data through visualisation.

- Construct and interpret confidence intervals.

- Build a regression model to explain variation in bike rentals.

- By the end, you will connect statistical concepts with practical Python analysis.

In [19]:
## Import libraries and data
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.float_format', lambda x: f'{x:,.3f}')
bikes = pd.read_csv('../Data/london_bikes.csv')
bikes["date"] = pd.to_datetime(bikes["date"])
bikes.head(10)

,date,bikes_hired,year,wday,month,week,cloud_cover,humidity,pressure,radiation,precipitation,snow_depth,sunshine,mean_temp,min_temp,max_temp,weekend
0,2010-07-30 00:00:00+00:00,6897,2010,Fri,Jul,30,6.000,65.000,"10,147.000",157.000,22.000,NaN,31.000,17.700,12.300,25.100,False
1,2010-07-31 00:00:00+00:00,5564,2010,Sat,Jul,30,5.000,70.000,"10,116.000",184.000,0.000,NaN,47.000,21.100,17.000,23.900,True
2,2010-08-01 00:00:00+00:00,4303,2010,Sun,Aug,30,7.000,63.000,"10,132.000",89.000,0.000,NaN,3.000,19.300,14.600,23.400,True
3,2010-08-02 00:00:00+00:00,6642,2010,Mon,Aug,31,7.000,59.000,"10,168.000",134.000,0.000,NaN,20.000,19.500,15.600,23.600,False
4,2010-08-03 00:00:00+00:00,7966,2010,Tue,Aug,31,5.000,66.000,"10,157.000",169.000,0.000,NaN,39.000,17.900,12.100,20.100,False
5,2010-08-04 00:00:00+00:00,7893,2010,Wed,Aug,31,6.000,75.000,"10,080.000",121.000,32.000,NaN,15.000,17.400,14.700,22.600,False
6,2010-08-05 00:00:00+00:00,8724,2010,Thu,Aug,31,4.000,58.000,"10,125.000",227.000,0.000,NaN,79.000,17.300,11.900,21.400,False
7,2010-08-06 00:00:00+00:00,9797,2010,Fri,Aug,31,6.000,75.000,"10,148.000",141.000,26.000,NaN,25.000,16.400,11.300,21.800,False
8,2010-08-07 00:00:00+00:00,6631,2010,Sat,Aug,31,7.000,78.000,"10,148.000",112.000,10.000,NaN,12.000,18.900,15.900,24.500,True
9,2010-08-08 00:00:00+00:00,7864,2010,Sun,Aug,31,4.000,64.000,"10,194.000",201.000,0.000,NaN,62.000,19.000,13.500,25.100,True

In [23]:
# Lets view all of the columns 
display(bikes.columns)

Index(['date', 'bikes_hired', 'year', 'wday', 'month', 'week', 'cloud_cover',
       'humidity', 'pressure', 'radiation', 'precipitation', 'snow_depth',
       'sunshine', 'mean_temp', 'min_temp', 'max_temp', 'weekend'],
      dtype='str')

**1. Data Cleaning**

Check for missing values across columns. How would you handle them?

Inspect the date column and ensure it is correctly formatted as datetime. Extract useful features (year, month, day, day of week, season).

Convert categorical variables (e.g., season, weather) to appropriate categories in Python.

Ensure numeric columns (e.g., bikes rented, temperature) are in the right format.

In [ ]:

print("Base Dataset Null values count:", bikes.isnull().sum().sum())

# to create a seasosn column lets find out the unique months 
print(bikes["month"].unique())
seasons = {
    "Winter": ["Dec", "Jan", "Feb"],
    "Spring": ["Mar", "Apr", "May"],
    "Summer": ["Jun", "Jul", "Aug"],
    "Fall": ["Sep", "Oct", "Nov"]
}

bikes.describe()

Base Dataset Null values count: 675
<StringArray>
['Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr', 'May',
 'Jun']
Length: 12, dtype: str

,bikes_hired,year,week,cloud_cover,humidity,pressure,radiation,precipitation,snow_depth,sunshine,mean_temp,min_temp,max_temp
count,"4,934.000","4,934.000","4,934.000","4,901.000","4,851.000","4,903.000","4,894.000","4,903.000","4,632.000","4,903.000","4,903.000","4,872.000","4,903.000"
mean,"26,448.566","2,016.823",26.896,4.918,75.710,"10,153.097",118.182,17.354,0.015,41.232,12.052,8.061,16.057
std,"9,677.635",3.910,15.158,2.368,11.234,105.267,89.454,38.244,0.235,38.966,5.721,5.266,6.613
min,0.000,"2,010.000",1.000,0.000,33.000,"9,668.000",2.000,0.000,0.000,0.000,-4.100,-9.400,-1.200
25%,"19,604.000","2,013.000",14.000,3.000,68.000,"10,091.000",40.000,0.000,0.000,5.000,7.700,4.200,11.000
50%,"26,129.000","2,017.000",27.000,5.000,77.000,"10,162.000",93.500,0.000,0.000,32.000,11.900,8.250,15.700
75%,"33,233.750","2,020.000",40.000,7.000,84.000,"10,224.000",186.000,18.000,0.000,67.000,16.600,12.200,21.000
max,"73,094.000","2,024.000",53.000,9.000,100.000,"10,477.000",402.000,516.000,7.000,147.000,30.900,22.300,40.200

In [20]:
## Your code goes here

# we dropped rows with missing values to better clean the data set
bikes_clean = bikes.dropna()

print(bikes_clean.dtypes)
bikes_clean.describe()

date             datetime64[us, UTC]
bikes_hired                    int64
year                           int64
wday                             str
month                            str
week                           int64
cloud_cover                  float64
humidity                     float64
pressure                     float64
radiation                    float64
precipitation                float64
snow_depth                   float64
sunshine                     float64
mean_temp                    float64
min_temp                     float64
max_temp                     float64
weekend                         bool
dtype: object

,bikes_hired,year,week,cloud_cover,humidity,pressure,radiation,precipitation,snow_depth,sunshine,mean_temp,min_temp,max_temp
count,"4,570.000","4,570.000","4,570.000","4,570.000","4,570.000","4,570.000","4,570.000","4,570.000","4,570.000","4,570.000","4,570.000","4,570.000","4,570.000"
mean,"26,853.637","2,017.095",26.894,4.940,75.935,"10,153.188",116.586,17.450,0.015,40.646,11.879,7.876,15.865
std,"9,735.944",3.679,15.419,2.362,11.248,107.052,89.811,38.260,0.236,38.813,5.739,5.290,6.645
min,0.000,"2,010.000",1.000,0.000,33.000,"9,668.000",2.000,0.000,0.000,0.000,-4.100,-9.400,-1.200
25%,"19,885.750","2,014.000",13.000,3.000,68.000,"10,089.000",39.000,0.000,0.000,4.000,7.600,4.000,10.900
50%,"26,711.000","2,017.000",27.000,5.000,77.000,"10,162.000",90.000,0.000,0.000,31.000,11.600,7.900,15.300
75%,"33,868.500","2,020.000",41.000,7.000,85.000,"10,226.000",185.000,18.000,0.000,66.000,16.400,12.000,20.800
max,"73,094.000","2,023.000",53.000,9.000,100.000,"10,477.000",402.000,516.000,7.000,147.000,30.900,22.300,40.200

**2. Exploratory Data Analysis (EDA)**

Plot the distribution of bikes rented.

Explore how rentals vary by season and month.

Investigate the relationship between temperature and bikes rented.

**Deliverables:**

At least 3 clear visualisations with captions.

A short written interpretation of key patterns (seasonality, weather effects, etc.).

In [ ]:
## Your code goes here

**3. Construct 95% confidence intervals for the mean number of bikes rented per season.**

Repeat the calculation per month.

Interpret the result:

What range of values do you expect the true mean to lie in?

Which seasons/months have higher or lower average demand?

Are there overlaps in the intervals, and what does that mean?

**Deliverables:**

A table or plot showing the mean and confidence intervals.

A short interpretation.

In [ ]:
## Your code goes here

**Regression Analysis**

What variables influence the number of bikes rented (y) and how? Build a regression model that best explains the variability in bikes rented.

**Interpret:**

Which predictors are significant?

What do the coefficients mean (in practical terms)?

How much of the variation in bike rentals is explained (R²)?

**Deliverables:**

Regression output table.

A short discussion of which factors matter most for predicting bike rentals.

In [ ]:
### Your code goes here

## Deliverables
A knitted HTML, one person per group to submit